// <auto-generated />
namespace DI.Infrastructure.Messaging.Models.Email.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AzureInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AzureInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201607132009454_AzureInitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
